@host = http://localhost
@port = 5139
@token = CfDJ8OwA7ffdXhlBktq22kF0NBhVIn82_HQ_MBw0dHCrMQJAanQhZFL5_b7xWa8llKQYPJDDXSqRX0-juiSnaHxjCQ6qH1XoLVUZe2Jh3d6T1nAMCDfv8olepiy9y7aQyCUNA9yJKPVF3zsbwIXH3eb2_GvM2douu2ffFsumiWmGRU68_HEK8-IpNQHK7w7DCjwdkyBYq7Fl-gjcZ8D7ILWhhRi3d-SeVBMSrRKM1P6eRfUSzl2EvlThXj248l5eGaXj1lqys6sxR6mElc4FzmVacIqDOKh_cOvyiQ5jx73otmZCqnGsZjpm6dzmHQxzwJl9PFafU-KivYBF49VPJtLYh60OKyi1aekfqAr-HBtWR3yU1n3IpF5pBnmnaQRz57AQrJMR3c67QhWUL_kZUqXRjx3TcNISDeIBtZmLRAhT8QnKLnveFxRf5P47EiFc2UOBJyxHs--gS8QvkGByzZ1MtcKEJV9HwFFDTTNthNWhdYaaXAM8LCgDkE5MomkelxK82E7bShndQXQxGY6AiV2Vu4Ts8CtYv0wevo3qI4saLKZyOvQZmtrIUZzx_zqe5ezcnsazVpMX-QwUcOaNrP7Q5hGj-2fdt3mVG1PVD575JD3oY0s4P4fbmOr8XhpcRBEDFfCn8ZdGzLVfH2Y6dk8065j8oDgOYQ2_4bAYMsJeZ3p45NcRoU04P_B6f_Pr-A7lHNQmXzz4HuSQb8QOJw1T0zvTbJiiXmnFXZL9ejAMEuEBuzb-0APFl8rt7aW2PlbWSkqA-HzzZWX1XhJcIk251cq1GlCFJXJPBFCgTb4AQiDMh8eIOQhk4mYa5P5353sNE9UFSOKMru_My2xRsWTSpMwjOPcONrxV13q_NIPAJzfn0f4oMBJ5OXOizv0OCAuOXA

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5139/api/restaurants?pageNumber=3&pageSize=10&sortBy=email
Authorization : Bearer CfDJ8OwA7ffdXhlBktq22kF0NBhSGLBD6xM4K8qonRQ7nuP5nfLPGWUAh0chDd7ARSiU72XFpFx3sSPqVErf1c85OsRcU_VE2Fc2C42Vj8m24J93wfqmHDr3H36vMBsEUXRAWIRjUhDYS-zJDhZLJRHb54kSSfzatQBBOJ23fvvnDF1FUvFgA9LiRrhW2nJ080CFK682oJwgqBctX1778o9x6OuDCjRPw5ZZJLHLZDgVfzqltzxlPY2vl3EJtANNpf2_QQwQlKzKxokh4SuBF_c_oZAslpdC4eNKNqMJ4UtEd9TAokj2a0KFxjRF1XrSiDM6UTeEah2eL9dlvmhM3n6KUAmaCBuEh4XeaHDn44jxDygt5EUhDfRRVmORkIGuJBBewYeS23KpdGwvsW24K7B2L4Zoqpc16ShXsHKAvNVXNooSLe0rGJ1SvuuwjvlhI7jO2PmuKcmYTbMvh9_aY3N2-sBK7yGJROLhwBNeIPCETcAk8iMhUhAdRi2Cj5VXocHI7B0CWknmhyxGQMarQ6qE4apBV4UKAMCVnM3TO9Y1W9H_o2BSJJFsd3ekjHu_z2fs9r5Azlqfbio75V0YKxzfb90RwOInVV7RCe8SQsIdpR5wuQHcKqZeUSsmHnNWoZMsQKcD658TBkCDWjoWLw2KqAv7D-NwcQp-j9wFKjHRGiflsQhc3RH_-vysoSAefit337gRnqVmQ170y2rLVAmZ6yH3_2XQ0kqD5eNSucP8wYJsNOqrrHT2M2ZFx6EF6Sfnw1-FMhMBIdl9FJYARHjQT_sX0jpCHYt6Csbg1EoGN4MBgQ8fl1pxsilNuH9-ZUIGtqa8qgpymiSVciafBzju8quPbgVwWDF9SG2w3L_NSHJzQxXMVALOZahO-h4ft8UFkg
###
POST http://localhost:5139/api/restaurants
Authorization : Bearer CfDJ8OwA7ffdXhlBktq22kF0NBiS_4wUQ5ju7uB01N3TzIgV9hsdtmpsBdpU4JaFEfd1ZIJuVuIbWb29LPB9v60E7yDb5HCDcs32HtNwOj3DbdmWLeucBeYsRhB4c8tqbEDKutPfezQ9zXl4TaAWFUP7apKVNUfF9SaGHux4z_AbzshGc9lO2bDWkoCfz_ym38bq45qM0D1RTRBlBTO1Nr4OfAjpnt8OrV4s8jLByde2NrNqzdKejaXbxjMhpf24MwaCob4S_RPRjpZVMWTZAtNNHCJi2q3f3PQCqa1VboxgSLS4UR8wXQdwck9BENfi8gTRk9HG5x0NmtuA-uKiBXqe7_EE90JDg07lIfbQrtWHM2k8m4OqK2DGEHBk-xB4IEhEAnyXOna5eZ8ICDc3s9jb1WxdRlrluHknPa93uToV3_bHGOPSmH0esrXGwIofhYszzFDOFvcq1_NePXvz8eG8-vy4lk6iRX0nNdGDrvhP8umr8755QX9vJaX6b33kMphurGkfSrNE4WL-nvBrvK17gNL5vOyNCqXZS3jBXVTJWqwlo0ZYv3WxM8GIx0cUNjiXrPa202vBgVP3uhSogX9or7csZ4y52Z0DpLHDaKwHtVG0Jc0E_NuiszgvzJlJsCt5qUyLitD1L6xw-BkT_06vaT7NXAWhyjzG9mFFWw_vmDdsJfcJON6fKK5NrYANbmoLfWSIBue9iu7n-0u0BRfztzN5eJ5TAZ6l3cVX2BlTZHR9GKtkuDQtiuYfLM5YY2eWFeTmep04bdV3ZB1nON3p-gv1TTqfJjbcb_iWgYROSjHf509uikDxcFQ4u6DrxxWCCYDQS9jSrp6hHPhHKIGwgRJkV6JJ5iRUkfmh4FZlCpJoVpghNIaqpsNN9OTG9uGT4Q
Content-type: application/json
{
  "name": "blabla1",
  "description": "ss",
  "category": "w",
  "hasDelivery": true,
  "phoneNumber": "01992922212",
  "contactEmail": "test@test.com",
  "street": "s",
  "city": "d",
  "postalCode": "01-110"
}
###
POST http://localhost:5139/api/identity/login
Content-type: application/json
{
  "email": "admin@test.com",
  "password": "Admin@123"
}
###
POST http://localhost:5139/api/identity/login
Content-Type: application/json

{
  "email": "Owner@test.com",
  "password": "Owner@123"
}


###
POST http://localhost:5139/api/identity/register
Content-type: application/json
{
  "email": "Owner@test.com",
  "password": "Owner@123"
}
